# Generated by Django 3.1.7 on 2021-03-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meublog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publicados',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
